### ISSUE TITLE
You could use Python's "enumerate" function.

### ISSUE THREAD

**Issue by prescod** [jake-87/asm-in-py#7]
https://github.com/jake-87/asm-in-py/blob/e255b06a9cc45a1361fae9adf206428c5d6b80e0/main.py#L19

**Comment by jake-87** [comment]
Looks good. I will try it out on the `testing` branch and compare it to the current solution.

**Comment by jake-87** [comment]
Hmm. Seems like this would be a large refactor, seeing as the code is very dependant on the `i` var. Perhaps i can find a workaround ?

**Comment by jake-87** [comment]
Nevermind! Found a workaround by not including I in the `for` statement and instead making it independent.

**Comment by prescod** [comment]
Sorry, I steered you wrong. Looking closer at the code I can see the function you should have used is range().

You ALMOST never need to increment counter variables explicitly in Python. 99% of the time that suggests a bug in your code.

The only times you need to increment counter variables explicitly is when you have complex conditionals which mean that sometimes you need to increment and sometimes you don't.

```
for i in range(len(code)): 
    if cfg.breakvar == 1: 
         break
    parse(code,i,cfg.data) 
    print(code[i]) i=i+1
```

**Comment by jake-87** [comment]
Oh, thanks. I will fix this, and actually, that could fix a null type error that's occurring on my  Linux machine. Thanks.
